files:
  - source: /fr-FR
    ignore:
      - ach-UGExampleachpo
    translation: /mariana/%two_letters_code%
    languages_mapping:
      two_letters_code:
        fr: France
        es-ES: Spain
        it: Italy
